POST http://localhost:8081/account-types
Content-Type: application/json
Accept: application/json

{
    "typeName": "handyman"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8081/account-types
Content-Type: application/json
Accept: application/json

{
  "typeName": "rancher"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
