--liquibase formatted sql

--changeset bnkspbrus:create-userAccount
create type payment_card as enum('Visa', 'MasterCard', 'Mir', 'UnionPay');

create table user_account
(
    id           int8 generated by default as identity,
    card_id      int8                  not null,
    payment_card payment_card          not null,
    user_id      int8 references users not null,
    primary key (id)
);