--liquibase formatted sql

--changeset bnkspbrus:create-users
set search_path to public;

create table users
(
    id         int8 generated by default as identity,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    phone      varchar(255),
    photo      bytea,
    primary key (id)
);