GET http://localhost:7070/accounts
Accept: application/json

###
POST http://localhost:7070/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "handyman1",
  "email": "handyman1",
  "phone": "123456789",
  "creation": "2016-01-25T21:34:55",
  "updating": "2016-01-25T21:34:55",
  "latitude": 1,
  "longitude": 0,
  "skills": ["a", "b"]
}

###
POST http://localhost:7070/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "handyman2",
  "email": "handyman2",
  "phone": "123456789",
  "creation": "2030-01-25T22:34:55",
  "updating": "2031-01-25T22:34:55",
  "latitude": 0,
  "longitude": 0,
  "skills": ["a", "b", "c"]
}

###
POST http://localhost:7070/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "handyman1",
  "email": "handyman1",
  "phone": "123456789",
  "creation": "2016-12-25T21:34:55",
  "updating": "2016-12-29T21:34:55",
  "latitude": 1,
  "longitude": 2,
  "skills": []
}

###
GET http://localhost:7070/accounts
Accept: application/json

###
