GET http://localhost:9090/accounts
Accept: application/json

###
POST http://localhost:9090/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "rancher1",
  "email": "rancher1",
  "phone": "123456789",
  "creation": "2016-01-25T21:34:55",
  "updating": "2016-01-25T21:34:55",
  "latitude": 1,
  "longitude": 0,
  "jobs": ["a", "b"]
}

###
POST http://localhost:9090/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "rancher2",
  "email": "rancher2",
  "phone": "123456789",
  "creation": "2030-01-25T22:34:55",
  "updating": "2031-01-25T22:34:55",
  "latitude": 0,
  "longitude": 0,
  "jobs": ["a", "b", "c"]
}

###
POST http://localhost:9090/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "rancher3",
  "email": "rancher3",
  "phone": "123456789",
  "creation": "2016-12-25T21:34:55",
  "updating": "2016-12-29T21:34:55",
  "latitude": 1,
  "longitude": 2,
  "jobs": []
}

###
GET http://localhost:9090/accounts
Accept: application/json

###
