# Sample Prometheus config
# This assumes that your Prometheus instance can access this application on localhost:8080

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'handyman'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'handyman:8080' ]
  - job_name: 'rancher'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'rancher:8082' ]
  - job_name: 'landscape'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'landscape:8081' ]