--liquibase formatted sql

--changeset bnkspbrus:create-gardener
set search_path to public;

create table gardener
(
    id         int8 generated by default as identity,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    phone      varchar(255),
    primary key (id)
)