--liquibase formatted sql

--changeset bnkspbrus:create-field

create table field
(
    id        int8 generated by default as identity,
    address   varchar(255)             not null,
    latitude  float8                   not null,
    longitude float8                   not null,
    gardener  int8 references gardener not null,
    area      geometry                 not null,
    primary key (id)
)