GET http://localhost:8082/fields
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8082/fields
Content-Type: application/json
Accept: application/json

{
  "gardenerId": {{gardener_1}},
  "address": "address 1",
  "latitude": 1,
  "longitude": 2,
  "areaWKT": "POLYGON((1 1, 1 2, 2 2, 2 1, 1 1))"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8082/fields
Content-Type: application/json
Accept: application/json

{
  "gardenerId": {{gardener_2}},
  "address": "address 2",
  "latitude": 2,
  "longitude": 2,
  "areaWKT": "POLYGON((0 0, 10 0, 10 10, 0 10, 0 0),(1 1, 1 2, 2 2, 2 1, 1 1))"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8082/fields
Content-Type: application/json
Accept: application/json

{
  "gardenerId": {{gardener_3}},
  "address": "address 3",
  "latitude": 3,
  "longitude": 2,
  "areaWKT": "POLYGON((0 0, 1 0, 1 1, 0 1, 0 0))"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
GET http://localhost:8082/fields
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###