GET http://localhost:9090/gardeners
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:9090/gardeners
Content-Type: application/json
Accept: application/json

{
  "login": "ivanobiwan",
  "email": "ivanobi@mail.ru",
  "phone": "123456789",
  "firstName": "ivan",
  "lastName": "ivanov",
  "latitude": 1,
  "longitude": 0
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("gardener_1", JSON.stringify(response.body))
%}
###
POST http://localhost:9090/gardeners
Content-Type: application/json
Accept: application/json

{
  "login": "bnkspb",
  "email": "bnksbp@mail.ru",
  "phone": "123456789",
  "firstName": "nikita",
  "lastName": "barsukov",
  "latitude": 0,
  "longitude": 0
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("gardener_2", JSON.stringify(response.body))
%}
###
POST http://localhost:9090/gardeners
Content-Type: application/json
Accept: application/json

{
  "login": "roman",
  "email": "roman@mail.ru",
  "phone": "123456789",
  "firstName": "roman",
  "lastName": "abramovich",
  "latitude": 2,
  "longitude": 0
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("gardener_3", JSON.stringify(response.body))
%}
###
GET http://localhost:9090/gardeners
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###