POST http://localhost:8082/orders/create
Content-Type: application/json
Accept: application/json

{
  "gardenId": {{field_1}},
  "skills": ["PLANT", "SOW"]
}

###
POST http://localhost:8082/fields/{{field_1}}/orders/create
Content-Type: application/json
Accept: application/json

{
  "gardenId": {{field_1}},
  "skills": ["PLANT", "SOW"]
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8082/fields/{{field_2}}/orders/create
Content-Type: application/json
Accept: application/json

{
  "gardenId": {{field_2}},
  "skills": ["SHOVEL"]
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
