--liquibase formatted sql

--changeset bnkspbrus:create-account
create type account_type_v1 as enum('handyman', 'rancher');

create table account
(
    id        int8 generated by default as identity,
    type_v1   account_type_v1,
    login     varchar(255) not null,
    email     varchar(255) not null,
    phone     varchar(255) not null,
    creation  timestamp without time zone not null,
    updating  timestamp without time zone not null,
    latitude  float8       not null default 0,
    longitude float8       not null default 0,
    primary key (id)
);