GET http://localhost:8080/accounts
Accept: application/json


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8080/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "handyman1",
  "email": "handyman1@mail.ru",
  "phone": "123456789",
  "firstName": "John",
  "lastName": "Doe",
  "latitude": 1,
  "longitude": 0,
  "skills": [
    "skill1",
    "skill2"
  ]
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8080/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "handyman2",
  "email": "handyman2@mail.ru",
  "phone": "123456789",
  "firstName": "John",
  "lastName": "Doe",
  "latitude": 1,
  "longitude": 1,
  "skills": [
    "skill1",
    "skill2",
    "skill3"
  ]
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
POST http://localhost:8080/accounts
Content-Type: application/json
Accept: application/json

{
  "login": "handyman3",
  "email": "handyman3@mail.ru",
  "phone": "123456789",
  "firstName": "John",
  "lastName": "Doe",
  "latitude": 1,
  "longitude": -1,
  "skills": []
}


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
GET http://localhost:8080/accounts
Accept: application/json


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
