GET http://localhost:7070/users
Accept: application/json

###
POST http://localhost:7070/users
Content-Type: application/json
Accept: application/json

{
  "skills": [
    "SHOVEL",
    "PLANT"
  ],
  "typeV2": {
    "id": 1,
    "typeName": "handyman"
  },
  "login": "login",
  "email": "email@mail.ru",
  "phone": "123456789",
  "firstName": "firstName",
  "lastName": "lastName",
  "creation": "2007-12-03T10:15:30",
  "updating": "2007-12-03T10:15:30",
  "latitude": 0,
  "longitude": 0
}

###