GET http://localhost:7070/users
Accept: application/json

###
POST http://localhost:7070/users
Content-Type: application/json
Accept: application/json

{
  "skills": [
    "SHOVEL",
    "PLANT"
  ],
  "login": "ivanobiwan",
  "email": "ivanobi@mail.ru",
  "phone": "123456789",
  "firstName": "ivan",
  "lastName": "ivanov",
  "latitude": 1,
  "longitude": 0
}

###
POST http://localhost:7070/users
Content-Type: application/json
Accept: application/json

{
  "skills": [
    "SHOVEL",
    "PLANT",
    "SOW"
  ],
  "login": "bnkspb",
  "email": "bnksbp@mail.ru",
  "phone": "123456789",
  "firstName": "nikita",
  "lastName": "barsukov",
  "latitude": 0,
  "longitude": 0
}

###
POST http://localhost:7070/users
Content-Type: application/json
Accept: application/json

{
  "skills": [
    "PLANT"
  ],
  "login": "roman",
  "email": "roman@mail.ru",
  "phone": "123456789",
  "firstName": "roman",
  "lastName": "abramovich",
  "latitude": 2,
  "longitude": 0
}

###
GET http://localhost:7070/users
Accept: application/json

###